kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: oci-fss
provisioner: oracle.com/oci-fss
parameters:
    # Insert mount target from the FSS here
  mntTargetId: ocid1.mounttarget.oc1.ap_tokyo_1.aaaaaa4np2snjryfnzzhillqojxwiotboawxi33lpfxs2mjnmfsc2mia